create DATABASE storage;

CREATE TABLE categories (
id SERIAL NOT NULL,
name CHARACTER VARYING(25) NOT NULL,
description CHARACTER VARYING(70) NOT NULL DEFAULT '',

PRIMARY KEY(id),
UNIQUE(name)
);

CREATE TABLE producers (
id SERIAL NOT NULL,
name CHARACTER VARYING(40) NOT NULL,
postal_code CHARACTER(15) NOT NULL,
country CHARACTER VARYING(30) NOT NULL,
region CHARACTER VARYING(30) NOT NULL,
locality CHARACTER VARYING(35) NOT NULL,
street CHARACTER VARYING(50) DEFAULT '',
building CHARACTER VARYING(18) DEFAULT '',

PRIMARY KEY(id)
);

CREATE TABLE goods (
id SERIAL NOT NULL,
name CHARACTER VARYING(30) NOT NULL,
sort CHARACTER VARYING(30) NOT NULL,
description CHARACTER VARYING(900) NOT NULL DEFAULT '',
category_id INT NOT NULL,
producer_id INT NOT NULL,

PRIMARY KEY(id),
FOREIGN KEY (category_id)
REFERENCES categories (id)
ON DELETE NO ACTION ON UPDATE NO ACTION,

FOREIGN KEY (producer_id)
REFERENCES producers (id)
ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TYPE unit_enum as ENUM('Í„', '„', 'Ú', '¯Ú', 'Â‰');

CREATE TABLE storehouse(
id SERIAL NOT NULL,
good_id INTEGER NOT NULL,
ttn_num VARCHAR(15),
date TIMESTAMPTZ NOT NULL DEFAULT now(),
unit unit_enum DEFAULT 'Í„',
quantity INTEGER NOT NULL,
price MONEY NOT NULL,

PRIMARY KEY(id),

FOREIGN KEY (good_id)
REFERENCES goods (id)
ON DELETE NO ACTION ON UPDATE NO ACTION
);